apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ken-view-bind
  namespace: dev
subjects:
- kind: User
  name: ken
  namespace: dev
roleRef:
  kind: Role
  name: dev-view
  apiGroup: rbac.authorization.k8s.io
