apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: otus
  namespace: prometheus
subjects:
- kind: Group
  name: system:serviceaccounts:prometheus
  apiGroup: rbac.authorization.k8s.io
  namespace: prometheus
roleRef:
  kind: Role
  name: otus
  apiGroup: rbac.authorization.k8s.io
