apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otus
subjects:
- kind: Group
  name: system:serviceaccounts:prometheus
  apiGroup: rbac.authorization.k8s.io
  namespace: prometheus
roleRef:
  kind: ClusterRole
  name: otus
  apiGroup: rbac.authorization.k8s.io
