---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: homework-issuer
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: irqoff@gmail.com
    privateKeySecretRef:
      name: homework-issuer
    solvers:
    - http01:
        ingress:
          class: nginx