apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    app: web
spec:
  containers:
  - name: web
    image: irqoff/otus_nginx:0.0.1
    volumeMounts:
    - name: app
      mountPath: /app
  - name: init
    image: busybox:1.34.1
    command: ["/bin/sh"]
    args: ["-c", "wget -O- https://tinyurl.com/otus-k8s-intro | sh"]
    volumeMounts:
    - name: app
      mountPath: /app
  volumes:
  - name: app
    emptyDir: {}
